# Generated by Django 4.2.3 on 2024-10-24 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_end_date_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
