# Generated by Django 4.2.3 on 2024-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
