# Generated by Django 4.2.3 on 2024-11-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
